### ISSUE TITLE
Getting error "Your local changes to the following files would be overwritten by merge: ..."

### ISSUE THREAD

**Issue by Sultron** [gofiber/basicauth#1]
Running go get -u github.com/gofiber/basicauth returns this error:

error: Your local changes to the following files would be overwritten by merge:
	go.mod
Please commit your changes or stash them before you merge.
Aborting
package github.com/gofiber/fiber: exit status 1

**Comment by Fenny** [comment]
@Sultron, are you still having problems running `go get` ?
