### ISSUE TITLE
how to use filter with the required bool as return ?

### ISSUE THREAD

**Issue by yonnic** [gofiber/basicauth#14]
well if i add a bool return to the handler to add it in filters, i cannot use the handler anywhere else anymore 
any solution?

**Comment by Fenny** [comment]
Coul you provide us with a code example to reproduce the issue?

**Comment by yonnic** [comment]
the filter require a func as `func(c *fiber.Ctx) bool` but everywhere else the type is `func(c *fiber.Ctx)`
i tried to do a wrapper func with the bool but this results in a full loss of auth for every route

`Filter: func(c *fiber.Ctx) bool {
			MyHandler(c)
			return true
		},`

**Comment by Fenny** [comment]
Returning true from the filter function will skip the auth middleware, see <https://github.com/gofiber/basicauth/blob/master/main.go#L68>
```go
		// Filter request to skip middleware
		if cfg.Filter != nil && cfg.Filter(c) {
			c.Next()
			return
		}
```

**Comment by yonnic** [comment]
if i add a bool to the handler, it gets invalid  `Cannot use 'MyHandler' (type func(c *fiber.Ctx) bool) as type Handler `

**Comment by Fenny** [comment]
In this example, you will parse the authentication fields if the request path equal `/login`
```go
package main

import (
  "github.com/gofiber/fiber"
  "github.com/gofiber/basicauth"
)

func main() {
  app := fiber.New()

  cfg := basicauth.Config{
    Filter: func(c *fiber.Ctx) bool {
        return c.Path() != "/login"
    },
    Users: map[string]string{
      "john":   "doe",
      "admin":  "123456",
    },
  }
  app.Use(basicauth.New(cfg))

  app.Get("/login", func(c *fiber.Ctx) {
    user := c.Locals("username").(string)
    pass := c.Locals("password").(string)
    c.SendString("Welcome " + user + ", we made sure your password " + pass + " is encrypted!")
  })

  app.Listen(":3000")
}
```

**Comment by yonnic** [comment]
ah now it makes sense how it's supposed to work, I was close with the wrapper but I didn't use the c.Path() to compare...
this really need to go into the example
