### ISSUE TITLE
[Documentation Request] Filter example

### ISSUE THREAD

**Issue by alex-savin** [gofiber/basicauth#9]
Hey Folks,

Would you mind please to post an example host to use a Filter in Config

Thank you in advance

**Comment by thomasvvugt** [comment]
Hi @alex-savin, the `Filter` configuration is has a type of `func(*fiber.Ctx) bool`.
An example might be to check for a `ctx.Locals`;

```go
  cfg := basicauth.Config{
    Users: map[string]string{
      "john":   "doe",
      "admin":  "123456",
    },
    Filter: func(c *fiber.Ctx) bool {
      admin, ok := c.Locals("admin").(bool)
      if !ok {
            return false
      }
      return admin
    },
  }
```

**Comment by alex-savin** [comment]
@thomasvvugt thank you very much!
